######################################################################
# Automatically generated by qmake (3.1) Thu Apr 27 20:04:46 2023
######################################################################

TEMPLATE = app
TARGET = app
INCLUDEPATH += .
QT += core widgets
QT += multimedia

INCLUDEPATH += gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0 gstreamer-app-1.0 gstreamer-audio-1.0 gstreamer-codecparsers-1.0 libcrypto libusb-1.0 openssl glib-2.0 gtk+-3.0 x11 protobuf sdl2 libudev alsa
INCLUDEPATH += src/components/content/android-head-unit/hu src/components/content/android-head-unit/common src/components/content/android-head-unit/core
INCLUDEPATH += src/components/content/android-head-unit/hu/generated.x64

CONFIG += link_pkgconfig
PKGCONFIG += gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0 gstreamer-app-1.0 gstreamer-audio-1.0 gstreamer-codecparsers-1.0 libcrypto libusb-1.0 openssl glib-2.0 gtk+-3.0 x11 protobuf sdl2 libudev alsa


# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/mainwindow.h \
           src/components/bottombar/bottombar.h \
           src/components/content/content.h \
           src/components/content/widget.h \
           src/components/topbar/topbar.h \
           src/components/bottombar/button/button.h \
           src/components/content/android-head-unit/aa_auto_controller.h \
           src/components/content/android-head-unit/aa_auto_widget.h \
           src/components/content/music-player/music_player.h \
           src/components/topbar/datetime/datetime.h \
           src/components/topbar/temperature/temperature.h \
           src/components/content/android-head-unit/common/audio.h \
           src/components/content/android-head-unit/common/command_server.h \
           src/components/content/android-head-unit/common/glib_utils.h \
           src/components/content/android-head-unit/core/aa_auto.h \
           src/components/content/android-head-unit/core/aa_auto_worker.h \
           src/components/content/android-head-unit/core/callbacks.h \
           src/components/content/android-head-unit/core/outputs.h \
           src/components/content/android-head-unit/hu/hu_aad.h \
           src/components/content/android-head-unit/hu/hu_aap.h \
           src/components/content/android-head-unit/hu/hu_ssl.h \
           src/components/content/android-head-unit/hu/hu_tcp.h \
           src/components/content/android-head-unit/hu/hu_usb.h \
           src/components/content/android-head-unit/hu/hu_uti.h \
           src/components/content/android-head-unit/common/json/json.hpp \
           src/components/content/android-head-unit/common/web++/web++.hpp \
           src/components/content/android-head-unit/core/bt/ub_bluetooth.h \
           src/components/content/android-head-unit/hu/generated.x64/hu.pb.h
SOURCES += app.cpp \
           src/mainwindow.cpp \
           src/components/bottombar/bottombar.cpp \
           src/components/content/content.cpp \
           src/components/topbar/topbar.cpp \
           src/components/bottombar/button/button.cpp \
           src/components/content/android-head-unit/aa_auto_widget.cpp \
           src/components/content/music-player/music_player.cpp \
           src/components/topbar/datetime/datetime.cpp \
           src/components/topbar/temperature/temperature.cpp \
           src/components/content/android-head-unit/common/audio.cpp \
           src/components/content/android-head-unit/common/command_server.cpp \
           src/components/content/android-head-unit/common/glib_utils.cpp \
           src/components/content/android-head-unit/core/aa_auto.cpp \
           src/components/content/android-head-unit/core/aa_auto_worker.cpp \
           src/components/content/android-head-unit/core/callbacks.cpp \
           src/components/content/android-head-unit/core/outputs.cpp \
           src/components/content/android-head-unit/hu/hu_aad.cpp \
           src/components/content/android-head-unit/hu/hu_aap.cpp \
           src/components/content/android-head-unit/hu/hu_ssl.cpp \
           src/components/content/android-head-unit/hu/hu_tcp.cpp \
           src/components/content/android-head-unit/hu/hu_usb.cpp \
           src/components/content/android-head-unit/hu/hu_uti.cpp \
           src/components/content/android-head-unit/common/web++/web++.cpp \
           src/components/content/android-head-unit/core/bt/ub_bluetooth.cpp \
           src/components/content/android-head-unit/hu/generated.x64/hu.pb.cc
